fix: try to fix

diff --git a/.github/workflows/publish-database.yml b/.github/workflows/publish-database.yml
--- a/.github/workflows/publish-database.yml
+++ b/.github/workflows/publish-database.yml
@@ -53,7 +53,9 @@ jobs:
         git config user.name "github-actions[bot]"
         git config user.email "github-actions[bot]@users.noreply.github.com"
         git tag $VERSION
-        git push origin $VERSION
+        if ! git push origin $VERSION; then
+          echo "Tag already exists or failed to push. Skipping this step."
+        fi
 
     - name: Pack with tag-based version
       if: ${{ env.TAG_EXISTS == 'false' }}
